[v3] Concept exercise - remote cars - guards/attrs
exercism/ruby pull request #1105
Opened 2021-02-20 20:46 UTC by neenjaw

Port of the Remote control car exercise.  Originally a C# exercise, but copied over from Elixir as source

2021-02-22 18:06 UTC, kotp requested changes

2021-02-22 18:06 UTC, kotp commented on exercises/concept/remote-control-car/remote_control_car_test.rb
> +  def test_new_car_hasnt_been_driven
```suggestion
  def test_new_car_has_not_been_driven
```

2022-10-16 19:39 UTC, kytrinyx commented
It's been 18 months since the last movement on this PR.

Does someone who was involved at the time have an idea of what it would take to get this over the finish line?

2022-10-25 21:59 UTC, kotp reviewed
Draft, so a comment rather than request for change.

2022-10-25 21:59 UTC, kotp commented on exercises/concept/remote-control-car/.docs/instructions.md
> +Cars start with full (100%) batteries. Each time you drive the car using the remote control, it covers 20 meters and drains one percent of the battery.
Single sentence per line, as per Exercism's [markdown specification].

[markdown specification]: https://exercism.org/docs/building/markdown/markdown

2023-03-28 03:55 UTC, closed without merging